### ISSUE TITLE
部署後的授權沒跳

### ISSUE THREAD

**Issue by jwjw141425** [jack24254029/lottery_bot#1]
按下 部署 後，會跳出以下頁面，點選 授予存取權 -> 選取自己的帳號 -> 進階 -> 點選 前往「XXX」(不安全)

按下部屬後沒有跳出這個選項，
後面LINE群內講話也Log不到excel內 想問怎麼解決呢

感謝大大分享詳盡教學，結果還是沒弄成功QQ

**Comment by jack24254029** [comment]
這個步驟的部屬應該是已經完成新增部署作業的流程，要按下視窗上的 `部署` 按鈕

我不太確定你這邊是不是說 Apps Script 編輯器上的 `部署` 按鈕

可以附上你說的沒有跳出這個選項的頁面嗎?

**Comment by jack24254029** [comment]
> 這個步驟的部屬應該是已經完成新增部署作業的流程，要按下視窗上的 `部署` 按鈕
> 
> 我不太確定你這邊是不是說 Apps Script 編輯器上的 `部署` 按鈕
> 
> 可以附上你說的沒有跳出這個選項的頁面嗎?

這個步驟有確認嗎?
會跳出授權的原因是因為會存取 Google 的相關服務 (Google Sheet)
請幫我確認會不會是 `SHEET_ID` 填錯了，導致他找不到你的 Google Sheet 進而判斷你沒有使用到 Google 的相關服務

![image](https://user-images.githubusercontent.com/13265628/149702195-fd555279-7cd7-423a-b95a-21f6d39eff9b.png)

**Comment by jwjw141425** [comment]
> > 這個步驟的部屬應該是已經完成新增部署作業的流程，要按下視窗上的 `部署` 按鈕
> > 我不太確定你這邊是不是說 Apps Script 編輯器上的 `部署` 按鈕
> > 可以附上你說的沒有跳出這個選項的頁面嗎?
> 
> 這個步驟有確認嗎? 會跳出授權的原因是因為會存取 Google 的相關服務 (Google Sheet) 請幫我確認會不會是 `SHEET_ID` 填錯了，導致他找不到你的 Google Sheet 進而判斷你沒有使用到 Google 的相關服務
> 
> ![image](https://user-images.githubusercontent.com/13265628/149702195-fd555279-7cd7-423a-b95a-21f6d39eff9b.png)

感謝大大回復，這是實作失敗的截圖，點選部屬完沒有跳授權就直接顯示完成部屬，
![131](https://user-images.githubusercontent.com/97824899/149714986-2b3ed4f8-c24d-4961-8732-c4184a38892e.jpg)
![132](https://user-images.githubusercontent.com/97824899/149714994-97f7059d-3a1f-45fc-86f6-ce820c165199.jpg)


後面我創了一個新的google帳號有成功了！
推測有可能原因是：
A帳號點選雲端apps Script自動跳去了預設使用的B帳號新增，兩個檔案不在同相同的帳號，所以沒有跳相關授權吧

**Comment by jack24254029** [comment]
恭喜你成功了~

另外提醒一下，後續修改都建議用 `管理部署作業` 哦
不然每次 `新增部署作業` 的話，網頁應用程式的網址是會變動的，那 Line 機器人的 Webhook URL 就要重新設定
