### ISSUE TITLE
完成上述步驟卡在機器人無法取得群組ID

### ISSUE THREAD

**Issue by skyblieve** [jack24254029/lottery_bot#2]
如題，都設定完後不知道哪裡出錯
拉機器進群組sheet的Log值沒有出現文字
求救Q_Q

**Comment by jack24254029** [comment]
- 請確認 Sheet ID 是否正確
- 請確認 Google Sheet 的連結公開是 `知道連結者皆可編輯`
- 請確認 Apps Script 編輯器左邊目錄的執行項目，裡面是否有東西 (如果可以，請附上執行項目的截圖)

**Comment by skyblieve** [comment]
![1642498830650](https://user-images.githubusercontent.com/50958583/149911360-a91c539d-5d09-4239-ba07-7dbdda802f87.jpg)
![1642498676482](https://user-images.githubusercontent.com/50958583/149911373-26e32c34-b209-4561-acb1-b09ebf844d03.jpg)
![1642498763255](https://user-images.githubusercontent.com/50958583/149911383-340684c6-6061-4db1-9e8b-0a1791dc1242.jpg)
你好，朋友昨天有成功，但換了群組就失敗了
我的部分則是維持失敗，機器人無法讀取群組ID
還不知道自己卡在哪一個環節出錯，再拜託你了

**Comment by jack24254029** [comment]
這邊跟你確定一下，是工作表的名稱要填 `Log` 不是整個檔案名稱哦
![image](https://user-images.githubusercontent.com/13265628/149960981-f7a12510-f8de-4a88-9fdf-e9b26e9b8cf9.png)

**Comment by jack24254029** [comment]
另外你朋友換群組會失敗的原因大概是後來有把 `TARGET_GROUP_ID` 填上，這個填上之後就只會讓那個群組可以跟機器人互動。

如果說要換群組的話，那 `Main.gs` 的第 21 行要加回去，再從 Log 撈出那個群組的 `Group ID`

**Comment by jack24254029** [comment]
我剛剛才注意到你說你朋友把全部程式碼放在一起也可以
沒錯哦~ 全部放在一起也是可以的，我當初會拆成四個檔案，只是當成分類而已

俗話說得好，垃圾都會分類了，程式碼可以不分類嗎?

**Comment by skyblieve** [comment]
> 這邊跟你確定一下，是工作表的名稱要填 `Log` 不是整個檔案名稱哦 ![image](https://user-images.githubusercontent.com/13265628/149960981-f7a12510-f8de-4a88-9fdf-e9b26e9b8cf9.png)

感謝，是工作表名稱沒改到，機器人有成功讀取到群組ID，但目前卡在使用指令無回應，哈哈~

**Comment by jack24254029** [comment]
因為我看不到你的程式碼，所以我只能請你再次確認 `Group ID` 是不是有填正確
可以先在群組隨便說一句話，再去 Log 那邊對一下內容是不是剛剛隨便說的那句話，再找裡面的 `Group ID`

可以確認一下找到 `Group ID` 之後的操作流程是不是跟以下的流程一致

1. 從工作表 Log 找到 `Group ID`
2. 將 `Group ID` 填回 Apps Script 上的 `TARGET_GROUP_ID`
3. 儲存專案 (！！！非常重要！！！)
4. 管理部署作業
5. 建立新版本
6. 部署

**Comment by skyblieve** [comment]
![1642564971273](https://user-images.githubusercontent.com/50958583/150061839-951aed1b-c803-4dbd-b1f1-f564c6943807.jpg)
![1642564914784](https://user-images.githubusercontent.com/50958583/150061844-95c422e4-f599-47d7-92c1-289583d74994.jpg)
有照上述步驟執行，程式碼也重新複製分四個檔案，但就卡住了~哈哈。

**Comment by skyblieve** [comment]
感謝，我成功了，複製錯Group ID，太謝謝你了
